// src/lib/components/Footer.svelte
<footer class="text-center p-3 bg-gray-300">
  <p>Made with [heart] <s>and Stack Overflow</s> by ThePoultryMan.</p>
  <p>Find more of my work on <a href="https://github.com/ThePoultryMan">GitHub</a></p>
  <p><a href="/special-thanks" class="underline">A special thank you</a> to all of the open source libraries that made this website possible.</p>
</footer>

// components/footer.vue
<template>
  <footer class="text-center p-3 bg-gray-300">
    <p>Made with <Icon name="ph:heart-straight-fill" class="text-red-400" /> <s>and stack overflow</s> by ThePoultryMan.</p>
    <p>Find more of my work on <NuxtLink class="text-blue-500 underline" to="https://github.com/ThePoultryMan/">GitHub</NuxtLink></p>
    <div>
      <p><NuxtLink to="/special-thanks/" class="text-blue-500 underline">A special thank you</NuxtLink> to all of the open source libraries that made this website possible.</p>
    </div>
  </footer>
</template>
